language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-24
    - android-28
    - sys-img-arm64-v8a-android-24

  licenses:
    - '.+'

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
    -
# Emulator Management: Create, Start and Wait
before_script:
  - android list target
  - echo no | android create avd --force -n test -t android-24 --abi default/arm64-v8a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  -
script:
  - ./gradlew build connectedCheck
