language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
    - android-28

  licenses:
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
script:
  - ./gradlew build connectedCheck
